application: thapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /styles
  static_dir: styles

- url: /tests
  static_dir: tests
  login: admin
  
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  
- url: /apple-touch-icon.png
  static_files: images/iphoneicon.png
  upload: images/iphoneicon.png

#- url: /robots.txt
#  static_files: files/robots.txt
#  upload: files/robots.txt

- url: /.*
  script: main.py

skip_files: |
 ^(.*/)?(
 ([Tt]humbs\.db)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.bak)|
 (.*\.psd)|
 (.*\.ai)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$

